/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import java.awt.Window;
import javax.swing.SwingUtilities;

/**
 *
 * @author orian
 */
public class NavBar extends javax.swing.JPanel {

    /**
     * Creates new form NavBar
     */
    public NavBar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton8 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btn_reservation = new javax.swing.JButton();
        btn_dashboard = new javax.swing.JButton();
        btn_rooms = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        btn_cusRegister = new javax.swing.JButton();
        btn_logout = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jButton8.setText("jButton8");

        setPreferredSize(new java.awt.Dimension(200, 453));

        jLabel4.setFont(new java.awt.Font("Roboto", 0, 10)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 153, 153));
        jLabel4.setText("Actions");

        btn_reservation.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        btn_reservation.setText("Reservation Form");
        btn_reservation.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_reservation.addActionListener(this::btn_reservationActionPerformed);

        btn_dashboard.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        btn_dashboard.setText("Dashboard");
        btn_dashboard.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_dashboard.addActionListener(this::btn_dashboardActionPerformed);

        btn_rooms.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        btn_rooms.setText("Rooms");
        btn_rooms.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_rooms.addActionListener(this::btn_roomsActionPerformed);

        jLabel2.setFont(new java.awt.Font("Roboto", 0, 10)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 153));
        jLabel2.setText("Pages");

        jButton5.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jButton5.setText("Customers");
        jButton5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        jButton6.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jButton6.setText("Reservation Report");
        jButton6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        btn_cusRegister.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        btn_cusRegister.setText("Customer Register");
        btn_cusRegister.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_cusRegister.addActionListener(this::btn_cusRegisterActionPerformed);

        btn_logout.setText("Logout");
        btn_logout.addActionListener(this::btn_logoutActionPerformed);

        jButton7.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jButton7.setText("Report");
        jButton7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        jLabel1.setBackground(new java.awt.Color(204, 204, 204));
        jLabel1.setFont(new java.awt.Font("Roboto", 0, 10)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 153, 153));
        jLabel1.setText("Reports");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(btn_reservation, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 2, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(btn_cusRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_dashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_rooms, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_logout, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_dashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_rooms, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_cusRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_reservation, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addGap(5, 5, 5)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(btn_logout)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_cusRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cusRegisterActionPerformed
         Window window = SwingUtilities.getWindowAncestor(this);
    if (window != null) {
        window.dispose();
        new CustomerRegister().setVisible(true);
    }
        

    }//GEN-LAST:event_btn_cusRegisterActionPerformed

    private void btn_dashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dashboardActionPerformed
        Window window = SwingUtilities.getWindowAncestor(this);
    if (window != null) {
        window.dispose();
        new Dashboard().setVisible(true);
    }
    }//GEN-LAST:event_btn_dashboardActionPerformed

    private void btn_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_logoutActionPerformed
                Window window = SwingUtilities.getWindowAncestor(this);
    if (window != null) {
        window.dispose();
        new LoginForm().setVisible(true);
    }
    }//GEN-LAST:event_btn_logoutActionPerformed

    private void btn_roomsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_roomsActionPerformed
                             Window window = SwingUtilities.getWindowAncestor(this);
    if (window != null) {
        window.dispose();
        new Rooms().setVisible(true);
    }
    }//GEN-LAST:event_btn_roomsActionPerformed

    private void btn_reservationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_reservationActionPerformed
                                   Window window = SwingUtilities.getWindowAncestor(this);
    if (window != null) {
        window.dispose();
        new ReservationForm().setVisible(true);
    }
    }//GEN-LAST:event_btn_reservationActionPerformed

public void addDashboardListener(java.awt.event.ActionListener listener) {
        btn_dashboard.addActionListener(listener);
    }

    public void addRoomsListener(java.awt.event.ActionListener listener) {
        btn_rooms.addActionListener(listener);
    }

    public void addCustomersListener(java.awt.event.ActionListener listener) {
        jButton5.addActionListener(listener);
    }

    public void addCustomerRegisterListener(java.awt.event.ActionListener listener) {
        btn_cusRegister.addActionListener(listener);
    }

    public void addReservationListener(java.awt.event.ActionListener listener) {
        btn_reservation.addActionListener(listener);
    }

    public void addReportListener(java.awt.event.ActionListener listener) {
        jButton6.addActionListener(listener);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cusRegister;
    private javax.swing.JButton btn_dashboard;
    private javax.swing.JButton btn_logout;
    private javax.swing.JButton btn_reservation;
    private javax.swing.JButton btn_rooms;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
