/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.Color;
import javax.swing.UIManager;
import mdlaf.MaterialLookAndFeel;
import mdlaf.themes.MaterialLiteTheme;
import org.kordamp.ikonli.materialdesign2.MaterialDesignA;
import org.kordamp.ikonli.materialdesign2.MaterialDesignC;
import org.kordamp.ikonli.materialdesign2.MaterialDesignU;
import org.kordamp.ikonli.swing.FontIcon;

/**
 *
 * @author orian
 */
public class Reservation extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Reservation.class.getName());

    /**
     * Creates new form Reservation
     */
    public Reservation() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txt_customer = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        lbl_customer_valid = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_room = new javax.swing.JTextField();
        lbl_room_valid = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1000, 600));

        jLabel1.setFont(new java.awt.Font("Ubuntu Sans Mono", 1, 14)); // NOI18N
        jLabel1.setText("Reservation");

        txt_customer.addActionListener(this::txt_customerActionPerformed);
        txt_customer.addPropertyChangeListener(this::txt_customerPropertyChange);

        jLabel2.setText("Customer Id ");

        jLabel3.setText("Room Id");

        txt_room.addActionListener(this::txt_roomActionPerformed);
        txt_room.addPropertyChangeListener(this::txt_roomPropertyChange);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txt_customer, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)
                        .addComponent(lbl_customer_valid, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txt_room, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbl_room_valid, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(99, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_customer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_room, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_room_valid, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_customer_valid, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(188, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_customerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_customerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_customerActionPerformed
    private void validateCustomer() {
        String cusId = txt_customer.getText();
    FontIcon materialIconCheck = FontIcon.of(MaterialDesignC.CHECK);
            FontIcon materialIconClose = FontIcon.of(MaterialDesignC.CLOSE);
            // 2. Customize size (in pixels) and color
            materialIconCheck.setIconSize(24);
            materialIconCheck.setIconColor(Color.GREEN);
            materialIconClose.setIconSize(24);
            materialIconClose.setIconColor(Color.RED);
        if (cusId == null || cusId.trim().isEmpty()) {
                lbl_customer_valid.setText("");
                return;
        }
    

        if (new controller.CustomerController().customerExist(cusId)) 
            {
                lbl_customer_valid.setIcon(materialIconCheck);
        } 
         else {
                lbl_customer_valid.setIcon(materialIconClose);
        }
}
    private void txt_customerPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txt_customerPropertyChange
     
        txt_customer.getDocument().addDocumentListener(new javax.swing.event.DocumentListener() {
              @Override
                public void insertUpdate(javax.swing.event.DocumentEvent e) {
                      validateCustomer(); 
                }

              @Override
                public void removeUpdate(javax.swing.event.DocumentEvent e) {
                    validateCustomer();
                  }

            @Override
              public void changedUpdate(javax.swing.event.DocumentEvent e) {
                    validateCustomer();
                  }
        });
       
    }//GEN-LAST:event_txt_customerPropertyChange

    private void txt_roomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_roomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_roomActionPerformed
  private void validateRoom() {
        String roomId = txt_room.getText();
    FontIcon materialIconCheck = FontIcon.of(MaterialDesignC.CHECK);
            FontIcon materialIconClose = FontIcon.of(MaterialDesignC.CLOSE);
            // 2. Customize size (in pixels) and color
            materialIconCheck.setIconSize(24);
            materialIconCheck.setIconColor(Color.GREEN);
            materialIconClose.setIconSize(24);
            materialIconClose.setIconColor(Color.RED);
        if (roomId == null || roomId.trim().isEmpty()) {
                lbl_room_valid.setText("");
                return;
        }
    

        if (new controller.RoomController().roomExist(roomId)) 
            {
                lbl_room_valid.setIcon(materialIconCheck);
        } 
         else {
                lbl_room_valid.setIcon(materialIconClose);
        }
}
    private void txt_roomPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txt_roomPropertyChange
             txt_room.getDocument().addDocumentListener(new javax.swing.event.DocumentListener() {
              @Override
                public void insertUpdate(javax.swing.event.DocumentEvent e) {
                      validateRoom(); 
                }

              @Override
                public void removeUpdate(javax.swing.event.DocumentEvent e) {
                    validateRoom();
                  }

            @Override
              public void changedUpdate(javax.swing.event.DocumentEvent e) {
                    validateRoom();
                  }
        });        // TODO add your handling code here:
    }//GEN-LAST:event_txt_roomPropertyChange

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
       try 
       {
             UIManager.setLookAndFeel(new MaterialLookAndFeel(new MaterialLiteTheme()));
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
        } catch (Exception ex) {
            System.out.println("view.Dashboard.main()");
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Reservation().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lbl_customer_valid;
    private javax.swing.JLabel lbl_room_valid;
    private javax.swing.JTextField txt_customer;
    private javax.swing.JTextField txt_room;
    // End of variables declaration//GEN-END:variables
}
